- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.4.2
  hooks:
  - id: flake8
    args: []
- repo: git://github.com/FalconSocial/pre-commit-python-sorter
  sha: 1.0.4
  hooks:
  - id: python-import-sorter
    args: ['--check-only']
